# Generated by Django 4.0 on 2022-01-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
