# Generated by Django 4.0 on 2022-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_orderitem_seller_alter_orderitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.TextField(default='Pending', null=True),
        ),
    ]
